spring:
  application:
    name: CitizenService
  datasource:
    url: jdbc:mysql://localhost:3306/micro_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database: org.hibernate.dialect.MySQL5InnoDBDialect


server:
  port: 8081

